<?php
$vars['helper']->setContainerClass('');
$vars['helper']->insertMessage();
$userId = $vars['userId'];

$vars['helper']->setTitle(__('Username edition'));
?>

<div id="link-back">
<a class="button" 
	href="<?php $vars['helper']->insertHref('Home')?>">
		<?php echo __('Home'); ?>
</a>
<a class="button" 
	href="<?php $vars['helper']->insertHrefWithNonce('displayProfile', 'Profile', 'display', array( 'userId' => $userId )); ?>">
		<?php echo __('Profile'); ?>
</a>
&nbsp;
<h4> <?php echo __('Username edition'); ?></h4>
</div>


<?php
if($vars['form']){
	echo '<div class="rounded-box centered_500">';
	$vars['form']->insert();
	echo '</div>';
}
?>
