<?php
$vars['helper']->setContainerClass('');
$vars['helper']->insertMessage();
$vars['helper']->addCssFile('profile_display.css');

$toolTemplate = $vars['toolTemplate'];
$tabTemplate = $vars['tabTemplate'];
$mainTemplate = $vars['mainTemplate'];

$user = $vars['user'];
$vars['helper']->setTitle( __( "%username%'s profile", array( '%username%' => $user->getUsername() ) ) );

?>

<div id="link-back">
<a class="button" 
	href="<?php echo $vars['helper']->createHref('Home')?>">
		<?php echo __('Home'); ?>
</a>
&nbsp;
<h4> <?php echo __('Profile'); ?></h4>
</div>

<!-- container of the profile, contains the both columns -->
<table class="profile-container">
	<tbody>
		<tr>
			<!-- first column: avatar + links -->
			<td class="profil-avatar-column">
				<?php $toolTemplate->insert(); ?>
			</td>
			<td class="vertical-bar"></td>
			<!-- second column: Username, age/gender / description / objective / quote -->
			<td class="profil-content-column">
				<?php $tabTemplate->insert(); ?>
				<?php $mainTemplate->insert(); ?>
			</td>
		</tr>
	</tbody>
</table>

