<?php
$vars['helper']->insertMessage();
$vars['helper']->insertMessage();
$vars['helper']->insertMessage();
if($vars['forum']){
	$name = $vars['forum']->getName();
	$descr = $vars['forum']->getDescription();
echo "name is [$name]";
echo "descr is [$descr]";
}else{
	echo 'currently no forum';
}

?><br>
<a href="<?php echo $vars['helper']->createHref('Forum', 'create')?>">Create</a><br/>
<a href="<?php echo $vars['helper']->createHref('Forum', 'viewAll')?>">View all</a><br/>
<a href="<?php echo $vars['helper']->createHref('Forum', 'index')?>">Go forum index</a><br/>
<a href="<?php echo $vars['helper']->createHref('Forum', 'displayCreate')?>">Go forum create</a><br/>