<h2>Test!!!</h2>

<?php $vars['helper']->insertMessage(); ?>
<a href="<?php echo $vars['helper']->createHref('Bipper', 'test')?>">Click here to bipper</a><br/>
<a href="<?php echo $vars['helper']->createHref('Bipper', 'testGet')?>">Click here to testGet</a><br/>
<a href="<?php echo $vars['helper']->createHref('Bipper', 'testPost')?>">Click here to testPost</a><br/>
<a href="<?php echo $vars['helper']->createHref('Bipper', 'testLoop')?>">Click here to testLoop</a><br/>
<a href="<?php echo $vars['helper']->createHref('Bipper', 'testChild')?>">Click here to testChild</a>
<br/>
<br/>
<a href="<?php echo $vars['helper']->createHref('Bipper', 'testMessage', array(), array('redirect' => true))?>">Click here to test the message system</a>
<br/>
<br/>
<a href="<?php echo $vars['helper']->createHref('Forum', 'index')?>">To forum</a><br/>
