<?php
$vars['helper']->setContainerClass('');
$vars['helper']->insertMessage();
$userId = $vars['userId'];
?>
<div id="link-back"><a class="button" href="<?php
$vars['helper']->insertHrefWithNonce('displayProfile', 'Profile', 'display', array('userId'=>$userId ));
?>"><?php echo __('Back to profile'); ?></a></div>

<?php
echo "<h3>".__('Profile form')."</h3>";
if($vars['form']){
	echo '<div class="rounded-box">';
	$vars['form']->insert();
	echo '</div>';
}
?>
<a href="<?php echo $vars['helper']->createHref('Home')?>"><?php echo __('Back home');?></a><br/>
