<?php
$vars['helper']->setContainerClass('');
$vars['helper']->insertMessage();
//$userId = $vars['userId'];
//$user = $vars['user'];
//$profile = $vars['profile'];
$profileTemplate = $vars['profileTemplate'];
$user = $vars['user'];
$vars['helper']->setTitle( __( "%username%'s profile", array( '%username%' => $user->getUsername() ) ) );
?>

<div id="link-back">
<a class="button" 
	href="<?php echo $vars['helper']->createHref('Home')?>">
		<?php echo __('Home'); ?>
</a>
&nbsp;
<h4> <?php echo __('Profile'); ?></h4>
</div>

<?php 
if($profileTemplate){
//	echo '<div class="rounded-box">';
	$profileTemplate->insert();
//	echo '</div>';
}
?>
