
<?php $vars['helper']->response->setTitle('Home'); ?>
<?php $vars['helper']->insertMessage(); ?>
<h2>Home!!!</h2>
<a href="<?php echo $vars['helper']->createHref('Bipper', 'test')?>">Click here to bipper test</a><br/>
<a href="<?php echo $vars['helper']->createHref('Bipper', 'home')?>">Click here to bipper bip</a><br/>
<a href="<?php echo $vars['helper']->createHref('Forum', 'displayForm')?>">forum displayForm</a><br/>
