<?php
use core\tools\Utils;
$vars['helper']->insertMessage();

$vars['helper']->addCssFile('topics_loop.css');
// to remove the container css class
$vars['helper']->setContainerClass('');

$pagination = $vars['pagination'];
$topicTemplate = $vars['topicTemplate'];
$topic = $vars['topic'];
$postsTemplate = $vars['postsTemplate'];
$posts = $vars['posts'];
$commentForm = $vars['commentForm'];
?>

<?php if($topic): // forum loop ?>
<!--	<div class="rounded-box">-->
		<!-- Link to the parent forum -->
		<div id="link-back">
			<a class="button" href="<?php $vars['helper']->insertHref('Forum', 'viewAll') ?>"><?php echo __('Back to discussion place'); ?></a>
		</div>
		<!-- title / content -->
		<?php $topicTemplate->insert(); ?>
		<!-- 1st pagination -->
		<?php $pagination->insert(); ?>
		<!-- posts -->
		<?php $postsTemplate->insert(); ?>
		<!-- 2nd pagination -->
		<?php $pagination->insert(); ?>
		<!-- form to comment -->
		<?php $commentForm->insert(); ?>
<!--	</div>-->
<?php else: // no topics in this forum ?>
	<?php $vars['helper']->addCssFile('messages.css'); ?>
	<div class="rounded-box pagged">
	<div class="message info centered"><?php echo __('No topic in this forum');?></div>
	</div>
<?php endif; ?>