<?php
$vars['helper']->insertMessage();
$vars['helper']->setContainerClass( 'width_40' );
$vars['helper']->setTitle(__('Lost password'));
$form = $vars['form'];
?>

<div id="link-back">
	<a class="button" 
		href="<?php $vars['helper']->insertHref('Connection')?>">
			<?php echo __('Back'); ?>
	</a>
	&nbsp;
	<h4> <?php echo __('Lost password'); ?></h4>
</div>

<div class="rounded-box">
	<?php $form->insert();?>
</div>

