<?php
$vars['helper']->setContainerClass('');
$vars['helper']->insertMessage();
$forumId = $vars['forumId'];
$topicId = isset($vars['topicId']) ? $vars['topicId'] : false;

$vars['helper']->setTitle(__('Topic edition'));
$instruction = $vars['instruction'];

$pageTitle = $vars['title'];
?>

<div id="link-back">
<a class="button" 
	href="<?php echo $vars['helper']->createHref('Home')?>">
		<?php echo __('Home'); ?>
</a>
<a class="button" 
	href="<?php $vars['helper']->insertHref( 'Forum', 'displaySingleForum', array('forumId'=>$forumId )); ?>">
		<?php echo __('Discussions'); ?>
</a>
<?php if(false !== $topicId): ?>
<a class="button" 
	href="<?php $vars['helper']->insertHref('Topic', 'displaySingleTopic', array('topicId' => $topicId, 'forumId' => $forumId )); ?>">
		<?php echo __('Topic'); ?>
</a>
<?php endif; ?>
&nbsp;
<h4> <?php echo $pageTitle; ?></h4>

<?php $instruction->insertButton();?>

</div>

<?php $instruction->insert();?>
<?php
if($vars['form']){
	echo '<div class="rounded-box">';
	$vars['form']->insert();
	echo '</div>';
}
?>
